### PR TITLE
[FEATURE] Data will now use json

### PR DESCRIPTION
**Pull request by SandroCoutinho**
Data will now be loaded from `.json` instead of `.txt` or `.cfg` simply for readability sake.

DO NOT PUSH UNTIL I NOTIFY

### CODE REVIEW

**Comment by SandroCoutinho** [comment]
Will do.

**Comment by SandroCoutinho** [comment]
Npc drop's used to be hardcoded, I made it use json instead. If you wish to edit a Npc's drop you simply search by the npcId.

**Comment by Ceikry** [comment]
Looks pretty cool. I converted all the configs and such to JSON for 2009scape a few weeks ago, did player saves over the past couple days. It's a much nicer way of doing things.

**Comment by dginovker** [comment]
Testing now

**Pull request merged**
